### ISSUE TITLE
SaveSettings shouldnt be a MonoBehaviour

### ISSUE THREAD

**Issue by duencil** [GreatArcStudios/unitypausemenu#1]
no reason I can see that SaveSettings inherits from MonoBehaviour - its not meant as a gameobject component, and the fact that it is produces an error when you create it with new in PauseManager.cs.  In my modified version, I replaced the SaveSettings Start method with a constructor, and also moved the LoadSettings out of there, to have it called by PauseManager at an appropriate time.  I also moved the try catch around LoadSettings to inside the method.

**Comment by GreatArcStudios** [comment]
Thanks for opening the issue. Can you please submit a pull request?

**Comment by GreatArcStudios** [comment]
Implemented your changes.

**Comment by duencil** [comment]
Awesome, thanks

**Comment by GreatArcStudios** [comment]
No problem.
