### ISSUE TITLE
Cursor control

### ISSUE THREAD

**Issue by duencil** [GreatArcStudios/unitypausemenu#2]
using cursor keys/gamepad to navigate the pause menu is problematic. When a menu appears, nothing is highlighted by default.  The menu doesnt respond to the Cancel key to go back / exit the current menu.  When a slider or toggle option is selected, nothing is highlighted.  When Quit is pressed, selection doesnt seem to move to the quit submenu.

**Comment by GreatArcStudios** [comment]
Can you please elaborate on the cancel key issue?

**Comment by duencil** [comment]
well the EventHandler sends a cancel event to the selected object when the [StandaloneInputModule](http://docs.unity3d.com/Manual/script-StandaloneInputModule.html) detects that the cancel key or button has been pressed.   

Nothing is being done in response to that.  An event trigger needs to be added to each object that will handle the events. https://unity3d.com/learn/tutorials/modules/beginner/ui/ui-events-and-event-triggers

Normal menu behaviour would be to exit the current page and return to the previous one, or exit the Pause menu if is the top level

**Comment by GreatArcStudios** [comment]
Oh yeah, I see what you mean. I never got around to that. I'll add it in along with the other fixes.

**Comment by GreatArcStudios** [comment]
Fixed

**Comment by duencil** [comment]
Can I reopen this? Cancel functionality is added, but that was just one of three issues here with cursor control.  We still have outstanding:

1 When a menu appears, nothing is highlighted by default. 
2 When a slider or toggle option is selected, nothing is highlighted.You can see this in the Graphics menu trying to navigate over the options using cursors / controller buttons

Edit: though I can add comments, seems I cant reopen it, so I'll open a new issue instead
