### ISSUE TITLE
Duplicated fields and logic

### ISSUE THREAD

**Issue by duencil** [GreatArcStudios/unitypausemenu#3]
a few points here bundled into 1 issue.

the SaveSettings methods LoadGameSettings and SaveGameSettings could take the PauseManager as a parameter, so you dont need all those static fields on the PauseManager

There seems to be no reason for the ReadJson class to exist.  You use it to read from Json, but you use another class (SaveSettings) to write to Json, and are duplicating fields in both, creating unnecessary overhead when a user wants to add or remove fields to keep both in sync.  Just read from SaveSettings too.

SaveSettings duplicates a lot of fields from PauseManager.  It also only sets and uses those fields in the method SaveGameSettings.  Right now there is no reason that the class should exist for longer than the call to SaveGameSettings.  If PauseManager is to keep an instance of SaveGameSettings, it probably should not also have its own copy of settings outside that instance, as its just duplicated data, creating overhead when a user wants to add or remove fields.  

SaveGameSettings also duplicates a lot of logic from PauseManager for how settings interact with things like the QualitySettings.  I'd suggest adding Properties (get; set; ) to just one place (either the PauseManager or the SaveSettings) for accessing each controlled setting, keeping the logic for how it interacts with Unity in one place.

**Comment by GreatArcStudios** [comment]
Thanks for the tips, I'll take a look this weekend.
