### ISSUE TITLE
SaveSettings has self referential jsonString as member

### ISSUE THREAD

**Issue by duencil** [GreatArcStudios/unitypausemenu#4]
SaveSettings has a field called jsonString as a member

during loading this is not used, a string is passed from Pause Menu instead
during saving, this string is filled with the serialized conversion of the SaveSettings structure to Json

So the first time that JsonUtility.ToJson is called that string will be empty, but on each successive save the jsonString member will contain the entire last  serialization of SaveSettings structure as json, and will get added to the current serialization as a member.  Hence the save data size will grow for no good reason.

The solution is simple, remove the jsonString member from SaveSettings, make it a local variable in SaveGameSettings instead.

**Comment by GreatArcStudios** [comment]
Fixed!
