### ISSUE TITLE
inconsistency in file operations

### ISSUE THREAD

**Issue by duencil** [GreatArcStudios/unitypausemenu#5]
SaveSettings.LoadGameSettings takes a string to load from (containing the serialized json data already read from a file by the caller).  It does some exception handling for if the file doesnt exist which makes no sense in this context - it should be done in the caller as things stand.

In contrast SaveSettings.SaveGameSettings reads the string from a file internally.  

It is inconsistant to have the file reading done externally for one operation and internally for another.  

My first suggestion would be to make file reading done internally in both cases to hide those implementational details from the caller.  Though there could be an argument for making the SaveSettings more flexible by not tying it to saving its data in any particular place or manner, letting the caller do it, in which case you should have SaveGameSettings return its string rather than save it.  But either way consistency is key.

**Comment by GreatArcStudios** [comment]
I've made LoadGameSettings read the file internally in the method. I think this is what you're getting at. If not, just reopen the issue, and I'll fix it.

**Comment by duencil** [comment]
Thanks, yes that would have been my first suggestion

**Comment by GreatArcStudios** [comment]
I'll leave SaveSettings the way it is for now as it works stably.

**Comment by duencil** [comment]
this fix hasnt been commited yet right, despite you closing the issue?  The current repository doesnt have LoadGameSettings reading the file internally.

**Comment by duencil** [comment]
Btw, I cant reopen a closed issue (unless I closed it), without being a collaborator of a repo

**Comment by GreatArcStudios** [comment]
I've made it so LoadGameSettings parses the json file inside the method, which is what SaveGameSettings does. If you mean that I should get rid of readString parameter on LoadGameSettings then I'll probably just create a readString or something on SaveGameSettings.

**Comment by duencil** [comment]
What I mean is that LoadGameSettings should load the file (with File.ReadAllText, and then parse it)

```
String readString = File.ReadAllText(Application.persistentDataPath + "/" + fileName);
SaveSettings read = JsonUtility.FromJson<SaveSettings>(readString);

```

just as SaveGameSettings currently creates a json string and saves it to a file:

```
string jsonString = JsonUtility.ToJson(this);
File.WriteAllText(Application.persistentDataPath + "/" + fileName, jsonString);
```

in the current repository the File.ReadAllText operation is being done externally and I think that is worong

**Comment by duencil** [comment]
Also while we are on this, it is probably better and less confusing in LoadGameSettings to do the json parsing  into the current SaveSettings object (this) rather than create a new temporary one.  So instead of:

`SaveSettings read = JsonUtility.FromJson<SaveSettings>(readString);`

you would do:

`JsonUtility.FromJsonOverwrite(readString, this);
`

**Comment by GreatArcStudios** [comment]
Thanks for the tips, they've been implemented.
