### ISSUE TITLE
Problem With Menu

### ISSUE THREAD

**Issue by RusticBanana** [GreatArcStudios/unitypausemenu#8]
I seem to be having a problem with this. After I install it I try it in game and the menu opens but when i move my mouse it moves the game behind the menu. Then when i click on one of the buttons it make the mouse icon disappear.

**Comment by GreatArcStudios** [comment]
Are you using the latest github version? If so, you may need to reassign all of the fields in the inspector for the pause menu.

**Comment by RusticBanana** [comment]
Yes I am using the latest github version. I have assigned all of the fields but it is still doing it.

**Comment by RusticBanana** [comment]
https://gyazo.com/56811bf1ed4b25b09e4084b401cde336

**Comment by RusticBanana** [comment]
https://gyazo.com/108a5261e9bcd29e50ee28b6e1f55cad
https://gyazo.com/4424d129a7a87e3906b147361fc33684

**Comment by GreatArcStudios** [comment]
You'll have to disable the mouse look script in the update statement. Specifically, in this if statement:
`  if (Input.GetKeyDown(KeyCode.Escape) && MainPanel.active == false)`
You can disable a script by using this code:
Put this with the rest of the member declarations 
`
public MonoBehaviour LookScript;
`
Put this in the if statement
`LookScript.enabled = false;`
Then reactivate the script in the resume method by doing the opposte of disabling the script.

**Comment by RusticBanana** [comment]
ok, so now it freezes the background but now I can no longer see my mouse icon.

**Comment by GreatArcStudios** [comment]
You may need to change around the look script.
