### ISSUE TITLE
Coroutine Utilities obsolete since unity 5.4

### ISSUE THREAD

**Issue by soraphis** [GreatArcStudios/unitypausemenu#9]
[(WaitForRealTime Code Reference)](https://github.com/GreatArcStudios/unitypausemenu/blob/master/Pause%20Menu%20Assetstore/Assets/Pause%20Menu%20Assets/Scripts/Utlities/CoroutineUtlities.cs#L9)

The Coroutine Utilities class contains only one method, this method is not necessary anymore, with unity 5.4 there is a method: [WaitForSecondsRealTime](https://docs.unity3d.com/ScriptReference/WaitForSecondsRealtime.html) in the Unity API

**Comment by GreatArcStudios** [comment]
Yup. I'll keep this in for devs using versions of Unity less than 5.4.

**Comment by GreatArcStudios** [comment]
Updated readme to reflect changes
